FROM python:3.9-alpine
RUN apk update && apk add build-base linux-headers

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

EXPOSE 5000

CMD [ "python3", "-m", "flask", "run", "--host=0.0.0.0", "--reload", "--no-debugger"]

# In this version, it is necessary to create a volume
# Example: docker run -p 5000:5000 -v /route/source/code:/app container_name